matrix:
  include:
    # R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
    - language: r
      r:
        - release
      sudo: required
      cache: packages
      before_install:
        - sudo apt-get install -y libv8-dev
    - language: node_js
      node_js:
        - "11.4.0"
      addons:
        - chrome: stable